### ISSUE TITLE
Icon doesn't always change

### ISSUE THREAD

**Issue by malvese** [ljacobs-sml/kirby-accordionHeadlineField#1]
If you expand a panel, and another panel is already expanded, then the previously expanded panel will collapse but keep its "-" icon.

![panelcollapse](https://cloud.githubusercontent.com/assets/193492/6902327/635e58ec-d713-11e4-82c1-bd1fe74cf198.gif)

**Comment by crispconcepts** [comment]
This should be resolved in the latest. Thanks for letting me know!
