### ISSUE TITLE
Opening by default the first item (or any other)

### ISSUE THREAD

**Issue by labo-css** [ljacobs-sml/kirby-accordionHeadlineField#2]
Hi, i love this plugin but can we open the first headline?

**Comment by crispconcepts** [comment]
I just pushed a new commit that opens the first panel item by default. As for "any other", I'll consider the possibility of making this option an extension of the field rather than having the behavior ingrained in the JS as it is now.

**Comment by labo-css** [comment]
Wonderful :)
